spring.datasource.url=jdbc:postgresql://db:5432/jobfinder
spring.datasource.username=dev
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto= update
server.port=8081
#image.upload.directory= './'
#spring.security.allow-request-from = *
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator